#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;

const string YES = "Yes";
const string NO = "No";

bool solve(std::string S){
    if(65<=S.at(0) && S.at(0)<=90){
        for(int i=1;i<S.size();i++){
            if(97<=S.at(i) && S.at(i)<=122){
                continue;
            }
            else{
                return false;
            }
        }
        return true;
    }
    else{
        return false;
    }
}

// Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::string S;
    std::cin >> S;
    bool ans = solve(S);
    if(ans)
        cout << YES << endl;
    else{
        cout << NO << endl;
    }
    return 0;
}
