#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;

// Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    string str;
    cin >> str;
    
    int pointer = str.size()-1;

    while(str.at(pointer)=='C' && pointer>0){
        pointer--;
    }

    while(str.at(pointer)=='B' && pointer>0){
        pointer--;
    }

    while(str.at(pointer)=='A' && pointer>0){
        pointer--;
    }
    
    if(pointer<=0)
        cout << "Yes" << endl;
    else
        cout << "No" << endl;
        
    return 0;
}
