#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;


vector<char> solve(std::string S){
    vector<char> str_list;
    for(int i=0;i<S.size();i++){
        if(S.at(i)!='.')
            str_list.push_back(S.at(i));
        else
            str_list.clear();
    }

    return str_list;
}

// Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::string S;
    std::cin >> S;
    vector<char> ans;
    ans = solve(S);
    for(int i=0;i<ans.size();i++){
        cout << ans[i];
    }
    cout << endl;
    return 0;
}
