#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;



// Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    int Xsum=0;
    int Ysum=0;
    
    int n;
    cin >> n;
    
    for(int i=0;i<n;i++){
        int a,b;
        cin >> a >> b;
        Xsum+=a;
        Ysum+=b;
    }
    
    if(Xsum>Ysum)
        cout << "Takahashi" << endl;
    else if(Xsum<Ysum)
        cout << "Aoki" << endl;
    else
        cout << "Draw" << endl;
        
    return 0;
}
