#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;


long long solve(long long N, std::vector<long long> A){
    long long min=0;
    long long diff=0;
    //一つずつ足し合わせて最低値だったら抜き取る
    for(int i=0;i<N;i++){
        diff+=A[i];
        if(min>diff)
            min=diff;
    }

    long long pass = abs(min);
    pass += diff;

    return pass;
}

// Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    std::scanf("%lld", &N);
    std::vector<long long> A(N);
    for(int i = 0 ; i < N ; i++){
        std::scanf("%lld", &A[i]);
    }
    long long min = solve(N, std::move(A));
    cout << min << endl;
    return 0;
}
